language: cpp
os: linux
dist: trusty

install:
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update
  - sudo apt-get install ansible

script:
  - sudo ansible-playbook -i inventory provision.yml --skip-tags "uninstall-toolchain,dev-uninstall"
  - sudo ansible-playbook -i inventory provision.yml --tags "uninstall-toolchain,dev-uninstall"
