language: cpp
os: linux
dist: trusty

install:
  - apt-get install software-properties-common
  - apt-add-repository ppa:ansible/ansible
  - apt-get update
  - apt-get install ansible

script:
  - echo "Finished"
