---
- name: update repositories cache
  apt:
    update_cache: yes
  tags: pkg-install

- name: install common software
  apt:
    name={{ item }}
    state=present
  with_items:
    - git
    - mc
    - curl
    - sqlite3
    - python-pip
    - screen
  tags: pkg-install

- name: install python modules
  pip:
    name=MySQL-python
    state=present
  tags: pkg-install
