---
- name: update repositories cache
  apt:
    update_cache: yes
  tags: pkg-install

- name: install common software
  apt:
    name={{ item }}
    state=present
  with_items:
    - git
    - mc
    - curl
    - sqlite3
  tags: pkg-install
