---
- name: install apache2
  apt:
    name:  "{{ item }}"
    state: present
  with_items:
    - apache2
  tags: pkg-install

- name: install PHP5 and modules
  apt:
    name:  "{{ item }}"
    state: present
  with_items:
    - php5
    - php5-curl
    - php5-cli
    - php5-mysql
    - php-pear
    - php5-gd
  tags: pkg-install

- name: enable rewrite module
  command: a2enmod rewrite

- name: restart apache2
  service:
    name=apache2
    enabled=yes
    state=restarted
